In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
import xgboost as xgb
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense,Dropout
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import LabelEncoder, MinMaxScaler


In [2]:
dir = '/content/drive/MyDrive/Anit/Gym_Posture_Data/train_test'

X_train = np.load(dir + '/X_train.npy')
Y_train = np.load(dir + '/Y_train.npy')

X_test = np.load(dir + '/X_test.npy')
Y_test = np.load(dir + '/Y_test.npy')

print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(1339, 30, 33, 3)
(1339,)
(335, 30, 33, 3)
(335,)


##Decision Tree Model

In [3]:
X_train_reshaped = X_train.reshape(X_train.shape[0], -1)
X_test_reshaped = X_test.reshape(X_test.shape[0], -1)

# Create a decision tree classifier
clf = DecisionTreeClassifier(random_state=42)

# Train the model
clf.fit(X_train_reshaped, Y_train)

# Make predictions on the test set
Y_pred = clf.predict(X_test_reshaped)

# Evaluate the model
accuracy = accuracy_score(Y_test, Y_pred)
conf_matrix = confusion_matrix(Y_test, Y_pred)
classification_rep = classification_report(Y_test, Y_pred)

# Print the results
print(f"Accuracy: {accuracy:.2f}")
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", classification_rep)

Accuracy: 0.61
Confusion Matrix:
 [[123  59]
 [ 73  80]]
Classification Report:
               precision    recall  f1-score   support

           0       0.63      0.68      0.65       182
           1       0.58      0.52      0.55       153

    accuracy                           0.61       335
   macro avg       0.60      0.60      0.60       335
weighted avg       0.60      0.61      0.60       335



In [4]:
X_train_reshaped.shape

(1339, 2970)

In [5]:
# Import the necessary libraries
from sklearn import tree

# Get the feature names from your reshaped data
feature_names = [f'feature_{i}' for i in range(X_train_reshaped.shape[1])]

# Print the decision tree model summary
tree_summary = tree.export_text(clf, feature_names=feature_names)
print("Decision Tree Summary:\n", tree_summary)

Decision Tree Summary:
 |--- feature_294 <= 0.44
|   |--- feature_1545 <= 0.44
|   |   |--- class: 1
|   |--- feature_1545 >  0.44
|   |   |--- class: 0
|--- feature_294 >  0.44
|   |--- feature_1164 <= 0.54
|   |   |--- feature_137 <= 0.00
|   |   |   |--- feature_67 <= 0.44
|   |   |   |   |--- feature_559 <= 0.14
|   |   |   |   |   |--- class: 1
|   |   |   |   |--- feature_559 >  0.14
|   |   |   |   |   |--- class: 0
|   |   |   |--- feature_67 >  0.44
|   |   |   |   |--- class: 1
|   |   |--- feature_137 >  0.00
|   |   |   |--- feature_1632 <= 0.44
|   |   |   |   |--- feature_531 <= 0.48
|   |   |   |   |   |--- class: 1
|   |   |   |   |--- feature_531 >  0.48
|   |   |   |   |   |--- class: 0
|   |   |   |--- feature_1632 >  0.44
|   |   |   |   |--- class: 0
|   |--- feature_1164 >  0.54
|   |   |--- feature_175 <= 0.53
|   |   |   |--- feature_436 <= 0.27
|   |   |   |   |--- class: 1
|   |   |   |--- feature_436 >  0.27
|   |   |   |   |--- class: 0
|   |   |--- feature_

##Random Forest Model

In [6]:
# Create a Random Forest classifier
rf_clf = RandomForestClassifier(random_state=42)

# Train the model
rf_clf.fit(X_train_reshaped, Y_train)

# Make predictions on the test set
Y_pred_rf = rf_clf.predict(X_test_reshaped)

# Evaluate the model
accuracy_rf = accuracy_score(Y_test, Y_pred_rf)
conf_matrix_rf = confusion_matrix(Y_test, Y_pred_rf)
classification_rep_rf = classification_report(Y_test, Y_pred_rf)

# Print the results
print(f"Random Forest Accuracy: {accuracy_rf:.2f}")
print("Random Forest Confusion Matrix:\n", conf_matrix_rf)
print("Random Forest Classification Report:\n", classification_rep_rf)

Random Forest Accuracy: 0.40
Random Forest Confusion Matrix:
 [[ 49 133]
 [ 68  85]]
Random Forest Classification Report:
               precision    recall  f1-score   support

           0       0.42      0.27      0.33       182
           1       0.39      0.56      0.46       153

    accuracy                           0.40       335
   macro avg       0.40      0.41      0.39       335
weighted avg       0.41      0.40      0.39       335



##SVM Classifier

In [ ]:
# Create an SVM classifier
svm_clf = SVC(random_state=42)

# Train the model
svm_clf.fit(X_train_reshaped, Y_train)

# Make predictions on the test set
Y_pred_svm = svm_clf.predict(X_test_reshaped)

# Evaluate the model
accuracy_svm = accuracy_score(Y_test, Y_pred_svm)
conf_matrix_svm = confusion_matrix(Y_test, Y_pred_svm)
classification_rep_svm = classification_report(Y_test, Y_pred_svm)

# Print the results
print(f"SVM Accuracy: {accuracy_svm:.2f}")
print("SVM Confusion Matrix:\n", conf_matrix_svm)
print("SVM Classification Report:\n", classification_rep_svm)

SVM Accuracy: 0.47
SVM Confusion Matrix:
 [[  3 179]
 [  0 153]]
SVM Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.02      0.03       182
           1       0.46      1.00      0.63       153

    accuracy                           0.47       335
   macro avg       0.73      0.51      0.33       335
weighted avg       0.75      0.47      0.31       335



##XGBoost Classifier

In [ ]:
# Create an XGBoost classifier
xgb_clf = xgb.XGBClassifier(random_state=42)

# Train the model
xgb_clf.fit(X_train_reshaped, Y_train)

# Make predictions on the test set
Y_pred_xgb = xgb_clf.predict(X_test_reshaped)

# Evaluate the model
accuracy_xgb = accuracy_score(Y_test, Y_pred_xgb)
conf_matrix_xgb = confusion_matrix(Y_test, Y_pred_xgb)
classification_rep_xgb = classification_report(Y_test, Y_pred_xgb)

# Print the results
print(f"XGBoost Accuracy: {accuracy_xgb:.2f}")
print("XGBoost Confusion Matrix:\n", conf_matrix_xgb)
print("XGBoost Classification Report:\n", classification_rep_xgb)

XGBoost Accuracy: 0.75
XGBoost Confusion Matrix:
 [[ 97  85]
 [  0 153]]
XGBoost Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.53      0.70       182
           1       0.64      1.00      0.78       153

    accuracy                           0.75       335
   macro avg       0.82      0.77      0.74       335
weighted avg       0.84      0.75      0.74       335



##LSTM Model

In [ ]:
# Reshape X_train and X_test to have a 2D shape (number_of_samples, sequence_length * features)
X_train_reshaped = X_train.reshape(X_train.shape[0], -1)
X_test_reshaped = X_test.reshape(X_test.shape[0], -1)

# Use label encoder to convert binary labels to 0 and 1
label_encoder = LabelEncoder()
Y_train_encoded = label_encoder.fit_transform(Y_train)
Y_test_encoded = label_encoder.transform(Y_test)

# Reshape Y_train_encoded and Y_test_encoded to have a 2D shape (number_of_samples, 1)
Y_train_encoded = Y_train_encoded.reshape(-1, 1)
Y_test_encoded = Y_test_encoded.reshape(-1, 1)


# Define the LSTM model
model = Sequential()
model.add(LSTM(50, input_shape=(X_train_reshaped.shape[1], 1)))
model.add(Dense(1, activation='sigmoid'))

# Compile the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
model.fit(np.expand_dims(X_train_reshaped, axis=-1), Y_train_encoded, epochs=30, batch_size=32, validation_split=0.2)

# Evaluate the model
accuracy = model.evaluate(np.expand_dims(X_test_reshaped, axis=-1), Y_test_encoded)[1]
print(f"LSTM Accuracy: {accuracy:.2f}")

Epoch 1/30
34/34 [==============================] - 7s 116ms/step - loss: 0.6286 - accuracy: 0.6909 - val_loss: 0.5055 - val_accuracy: 0.8769
Epoch 2/30
34/34 [==============================] - 4s 107ms/step - loss: 0.6151 - accuracy: 0.6909 - val_loss: 0.4390 - val_accuracy: 0.8769
Epoch 3/30
34/34 [==============================] - 3s 79ms/step - loss: 0.6147 - accuracy: 0.6909 - val_loss: 0.4654 - val_accuracy: 0.8769
Epoch 4/30
34/34 [==============================] - 3s 78ms/step - loss: 0.6138 - accuracy: 0.6909 - val_loss: 0.4883 - val_accuracy: 0.8769
Epoch 5/30
34/34 [==============================] - 3s 79ms/step - loss: 0.6150 - accuracy: 0.6909 - val_loss: 0.4838 - val_accuracy: 0.8769
Epoch 6/30
34/34 [==============================] - 3s 95ms/step - loss: 0.6163 - accuracy: 0.6909 - val_loss: 0.4622 - val_accuracy: 0.8769
Epoch 7/30
34/34 [==============================] - 4s 122ms/step - loss: 0.6142 - accuracy: 0.6909 - val_loss: 0.4577 - val_accuracy: 0.8769
Epoch 8/30

KeyboardInterrupt: ignored

In [ ]:
# Normalize input data
scaler = MinMaxScaler()
X_train_normalized = scaler.fit_transform(X_train.reshape(-1, X_train.shape[-1]))
X_test_normalized = scaler.transform(X_test.reshape(-1, X_test.shape[-1]))

# Reshape X_train and X_test to have a 3D shape (number_of_samples, sequence_length, features)
X_train_reshaped = X_train_normalized.reshape(X_train.shape[0], X_train.shape[1], -1)
X_test_reshaped = X_test_normalized.reshape(X_test.shape[0], X_test.shape[1], -1)

# Use label encoder to convert binary labels to 0 and 1
label_encoder = LabelEncoder()
Y_train_encoded = label_encoder.fit_transform(Y_train)
Y_test_encoded = label_encoder.transform(Y_test)

# Reshape Y_train_encoded and Y_test_encoded to have a 2D shape (number_of_samples, 1)
Y_train_encoded = Y_train_encoded.reshape(-1, 1)
Y_test_encoded = Y_test_encoded.reshape(-1, 1)

# Define the LSTM model with dropout
model = Sequential()
model.add(LSTM(50, input_shape=(X_train_reshaped.shape[1], X_train_reshaped.shape[2])))
model.add(Dropout(0.2))  # Add dropout to reduce overfitting
model.add(Dense(1, activation='sigmoid'))

# Compile the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
model.fit(X_train_reshaped, Y_train_encoded, epochs=30, batch_size=32, validation_split=0.2)

# Evaluate the model
accuracy = model.evaluate(X_test_reshaped, Y_test_encoded)[1]
print(f"LSTM Accuracy: {accuracy:.2f}")

Epoch 1/30
34/34 [==============================] - 4s 28ms/step - loss: 0.6247 - accuracy: 0.6788 - val_loss: 0.4328 - val_accuracy: 0.8769
Epoch 2/30
34/34 [==============================] - 0s 9ms/step - loss: 0.6139 - accuracy: 0.6909 - val_loss: 0.4470 - val_accuracy: 0.8769
Epoch 3/30
34/34 [==============================] - 0s 9ms/step - loss: 0.6182 - accuracy: 0.6900 - val_loss: 0.4442 - val_accuracy: 0.8769
Epoch 4/30
34/34 [==============================] - 0s 9ms/step - loss: 0.6046 - accuracy: 0.6891 - val_loss: 0.4910 - val_accuracy: 0.8769
Epoch 5/30
34/34 [==============================] - 0s 8ms/step - loss: 0.5854 - accuracy: 0.6816 - val_loss: 0.4462 - val_accuracy: 0.8881
Epoch 6/30
34/34 [==============================] - 0s 9ms/step - loss: 0.5296 - accuracy: 0.6611 - val_loss: 0.2857 - val_accuracy: 0.8657
Epoch 7/30
34/34 [==============================] - 0s 9ms/step - loss: 0.5504 - accuracy: 0.6704 - val_loss: 0.4590 - val_accuracy: 0.8769
Epoch 8/30
34/34 [=